### ISSUE TITLE
Spec WDT

### ISSUE THREAD

**Issue by timkurvers** [timkurvers/blizzardry#17]

**Comment by NSElvis** [comment]
tihi

**Comment by timkurvers** [comment]
:open_mouth:

**Comment by timkurvers** [comment]
Covered by 4dfaad618723ba4bca63ae96662c2d857744c9d8, e4e9ea10b3719e2d898c78b6c32fe9b75039a244, 455d156e3e715bb81c8c93dfefb9ecb6f040c99e and 05c6c5c9b583c86c54d17c26f24aff6369591ab1.
